version: "3.2"

services:

  client:
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    command: "/usr/local/hadoop/bin/hadoop fs -ls /"
    extra_hosts:
     - "namenode:192.168.45.181"
     - "resourcemanager:192.168.45.182"

