version: "3.2"

services:

  client:
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTPS_PROXY}
    command: "/usr/local/hadoop/bin/hadoop fs -ls /"
    extra_hosts:
     - "h020nn:192.168.1.103"
     - "h020jt:192.168.1.104"
     - "h3nn:192.168.45.181"
     - "h3rm:192.168.45.182"

